### ISSUE TITLE
Error installing oodocx

### ISSUE THREAD

**Issue by TheFlatline** [etfre/oodocx#1]
I found this error while trying to install oodocx. I tried the same in a virtualenv, with still the same error.

$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing oodocx.egg-info/PKG-INFO
writing top-level names to oodocx.egg-info/top_level.txt
writing dependency_links to oodocx.egg-info/dependency_links.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'oodocx.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/oodocx
copying build/lib/oodocx/oodocx.py -> build/bdist.linux-x86_64/egg/oodocx
copying build/lib/oodocx/write_files.py -> build/bdist.linux-x86_64/egg/oodocx
copying build/lib/oodocx/**init**.py -> build/bdist.linux-x86_64/egg/oodocx
creating build/bdist.linux-x86_64/egg/oodocx/template
creating build/bdist.linux-x86_64/egg/oodocx/template/word
copying build/lib/oodocx/template/word/webSettings.xml -> build/bdist.linux-x86_64/egg/oodocx/template/word
copying build/lib/oodocx/template/word/document.xml -> build/bdist.linux-x86_64/egg/oodocx/template/word
copying build/lib/oodocx/template/word/stylesWithEffects.xml -> build/bdist.linux-x86_64/egg/oodocx/template/word
creating build/bdist.linux-x86_64/egg/oodocx/template/word/theme
copying build/lib/oodocx/template/word/theme/theme1.xml -> build/bdist.linux-x86_64/egg/oodocx/template/word/theme
copying build/lib/oodocx/template/word/settings.xml -> build/bdist.linux-x86_64/egg/oodocx/template/word
creating build/bdist.linux-x86_64/egg/oodocx/template/word/_rels
copying build/lib/oodocx/template/word/_rels/document.xml.rels -> build/bdist.linux-x86_64/egg/oodocx/template/word/_rels
copying build/lib/oodocx/template/word/fontTable.xml -> build/bdist.linux-x86_64/egg/oodocx/template/word
copying build/lib/oodocx/template/word/styles.xml -> build/bdist.linux-x86_64/egg/oodocx/template/word
creating build/bdist.linux-x86_64/egg/oodocx/template/docProps
copying build/lib/oodocx/template/docProps/core.xml -> build/bdist.linux-x86_64/egg/oodocx/template/docProps
copying build/lib/oodocx/template/docProps/app.xml -> build/bdist.linux-x86_64/egg/oodocx/template/docProps
creating build/bdist.linux-x86_64/egg/oodocx/examples
copying build/lib/oodocx/examples/example1.py -> build/bdist.linux-x86_64/egg/oodocx/examples
copying build/lib/oodocx/__init__.pyc -> build/bdist.linux-x86_64/egg/oodocx
copying build/lib/oodocx/helper_functions.py -> build/bdist.linux-x86_64/egg/oodocx
byte-compiling build/bdist.linux-x86_64/egg/oodocx/oodocx.py to oodocx.pyc
**SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/oodocx/oodocx.py', 630, 34, "                attributes={'val', 'subscript'})\n"))**

byte-compiling build/bdist.linux-x86_64/egg/oodocx/write_files.py to write_files.pyc
byte-compiling build/bdist.linux-x86_64/egg/oodocx/examples/example1.py to example1.pyc
byte-compiling build/bdist.linux-x86_64/egg/oodocx/helper_functions.py to helper_functions.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying oodocx.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying oodocx.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying oodocx.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying oodocx.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/oodocx-0.1.0-py2.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing oodocx-0.1.0-py2.6.egg
removing '/usr/lib/python2.6/site-packages/oodocx-0.1.0-py2.6.egg' (and everything under it)
creating /usr/lib/python2.6/site-packages/oodocx-0.1.0-py2.6.egg
Extracting oodocx-0.1.0-py2.6.egg to /usr/lib/python2.6/site-packages
SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/oodocx-0.1.0-py2.6.egg/oodocx/oodocx.py', 630, 34, "                attributes={'val', 'subscript'})\n"))

oodocx 0.1.0 is already the active version in easy-install.pth

Installed /usr/lib/python2.6/site-packages/oodocx-0.1.0-py2.6.egg
Processing dependencies for oodocx==0.1.0
Finished processing dependencies for oodocx==0.1.0

**Comment by etfre** [comment]
It looks like the installation was tripping up on a couple of syntax errors in the code. I think they should be fixed with the latest commit, so feel free to give it another go and let me know whether it works. Also, I've been primarily developing this in Python 3.3, and while several test runs of the latest commit with 2.7 have been successful, I can't guarantee similar results.

**Comment by TheFlatline** [comment]
Hi!
Yes now it works (well I managed to do a few simple "template substitution" in a docx in a django view without issues... now I will have to test some more advanced stuff, like generating tables). The only other issue I had was with OrderedDict, but this was due to CentOS still using python 2.6. I installed 2.7.5 and now it works.

Thanks for the fast reply!

**Comment by etfre** [comment]
No problem! Glad you got things working.
