### ISSUE TITLE
Correct way to format and merge cells in table

### ISSUE THREAD

**Issue by TheFlatline** [etfre/oodocx#3]
I'm trying to produce a (relatively) complex table with oodocx. Is there a way to merge cells ("colspan" like)?
Moreover, is it possible to format the cell background?

**Comment by etfre** [comment]
There's nothing currently built into oodocx for table formatting. It is entirely feasible to use lxml to poke around in conjunction with oodocx, however. For instance:

```
from oodocx import oodocx
from lxml import etree

d = oodocx.Docx()
mytable = oodocx.table([['1', '2', '3'], ['4', '5', '6']])
d.body.append(mytable)
for descendant in mytable.iter('{' + oodocx.NSPREFIXES['w'] + '}tcPr'):
    descendant.append(oodocx.makeelement('shd', attributes={'val': 'clear',
                                                       'themeFill': 'accent3',
                                                       'fill': '9BBB59',
                                                       'color': 'auto'}))
d.save('tabletest.docx')
```

This will create a table and fill the background of each cell with a shade of green. Check out the page [here](http://officeopenxml.com/WPtable.php) for an overview of tables with Open Office Xml. It looks like the equivalent for colspan is the &lt;w:gridSpan&gt; element, which is also a child of the &lt;w:tcPr&gt; element. You can find some documentation of table spanning [here](http://officeopenxml.com/WPtableGrid.php).

**Comment by TheFlatline** [comment]
Thanks, nice pointers!
