### ISSUE TITLE
Style shortcut keys don't work after saving

### ISSUE THREAD

**Issue by ajmirsky** [etfre/oodocx#5]
Using microsoft word 2011 for mac, you can assign a shortcut key to a specific style. Attached are the screenshots of where it is located in Word. By comparing two docx where the only difference is adding a shortcut key to the `Quote` style, it seems that an extra file gets added to the `word/` directory called `customizations.xml` which contains this snippet:

```
   <wne:keymaps>
    <wne:keymap wne:kcmprimary="105A">
     <wne:acd wne:acdname="acd0">
     </wne:acd>
    </wne:keymap>
   </wne:keymaps>
```

Did some research through the OOXML standard and I haven't found any documentation that describes this file. Or describes the `keymap` or `keymaps` tags. Perhaps it's just a matter of including this file, if it exists, from the original docx that was opened?

Can't upload them here but I can send you the two docx files if it would be helpful.

![shortcut key screen 1](https://f.cloud.github.com/assets/323371/1823346/23618124-717a-11e3-8d00-39032391316b.png)
![shortcut key screen 2](https://f.cloud.github.com/assets/323371/1823347/236279e4-717a-11e3-8868-20a31f32d2ec.png)

**Comment by etfre** [comment]
I wasn't able to recreate the problem using Word 2007 in Windows 7. 

Is `customizations.xml` showing up both in the input and the output documents, or is it getting dropped somewhere in between? You're sure that you're saving the shortcut in the .Docx file and not in Normal.dotm? Are you doing anything else in your program other than loading a Docx and saving it?

**Comment by ajmirsky** [comment]
my mistake. the original file was based on a dotx with the shortcut keys being referenced from there. so i changed them to save within the .docx file and all is working. apologies for the false alarm.
